controllers/PortfolioController.php
<?php

namespace app\controllers;

use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\db\Expression;
use app\models\Transfer;
use app\models\Asset;
use app\models\AssetPrice;
use app\models\Profit;
use app\models\Event;
use app\models\News;
use yii\data\ActiveDataProvider;
use app\models\FilterStatistic;

class PortfolioController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => [
                            'dashboard',
                            'index',
                            'profit',
                            'profit-update',
                            'profit-delete',
                            'price',
                            'price-update',
                            'price-delete',
                            'asset-update',
                            'asset-delete',
                            'transfer',
                            'transfer-delete',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionDashboard()
    {
        $query = Asset::find();
        $query->where('is_liability = 0');

        $assetProvider = new ActiveDataProvider(
            [
                'query' => $query
            ]
        );

        $cash = Asset::getOrCreateCash();

        $totalProfit = Asset::getProfitSum('asset');
        $totalValue = Asset::getValueSum('asset');
        $totalLiabilityValue = Asset::getValueSum('liability');
        //var_dump($totalTransfer); die();

        $filter = new FilterStatistic();

        $query = News::find();
        $newsProvider = new ActiveDataProvider(
            [
                'query' => $query
            ]
        );

        $query = Event::find();
        $eventProvider = new ActiveDataProvider(
            [
                'query' => $query
            ]
        );

//        var_dump($weekProfit, $monthProfit, $yearProfit);
//        var_dump($weekTransfer, $monthTransfer, $yearTransfer);
//        die();

        //profit table
        //yesterday
        $date = date("Y-m-d", strtotime("-1 days"));
        $date1 = date("Y-m-d", strtotime("today"));

        $yesterdayProfit = Asset::getProfitSum('asset', $date, null);
        $yesterdayValue = Asset::getValueSum('asset', $date);

        // $asset = Asset::find()->where(['id' => 14])->one();


        // var_dump($date);
        // var_dump($yesterdayValue);
        // var_dump($asset->getValue($date));
        // $yesterday1Value = Asset::getValueSum(null, $date1);
        // var_dump($date1);
        // var_dump($yesterday1Value);
        // var_dump($asset->getValue($date1));
        // die();

        //last week
        $date = date("Y-m-d", strtotime("-7 days"));

        $weekProfit = Asset::getProfitSum('asset', $date, null);
        $weekValue = Asset::getValueSum('asset', $date);

        //last month
        $date = date("Y-m-d", strtotime("-30 days"));

        $monthProfit = Asset::getProfitSum('asset', $date, null);
        $monthValue = Asset::getValueSum('asset', $date);

        //last year
        $date = date("Y-m-d", strtotime("-12 months"));

        $yearProfit = Asset::getProfitSum('asset', $date, null);
        $yearValue = Asset::getValueSum('asset', $date);

        //all
        $allProfit = Asset::getProfitSum('asset');
        
        //Year To Date (YTD)
        $date = date("Y-m-d", strtotime("first day of jan this year"));

        $ytdProfit = Asset::getProfitSum('asset', $date, null);
        $ytdValue = Asset::getValueSum('asset', $date);


        $data = ['allModels' => [
        [
            '<strong>Value</strong>',
            sprintf("%01.2f USD", ($totalValue))
        ],
        [
            'Yesterday',
            sprintf("%01.2f USD", ($yesterdayProfit))
            . ' ('
            . sprintf("%.2f%%", ($yesterdayValue != 0?($yesterdayProfit)/$yesterdayValue:1) * 100)
            . ')'
        ],
        [
            'Week',
            sprintf("%01.2f USD", ($weekProfit))
            . ' ('
            . sprintf("%.2f%%", ($weekValue != 0?($weekProfit)/$weekValue:1) * 100)
            . ')'
        ],
        [
            'Month',
            sprintf("%01.2f USD", ($monthProfit))
            . ' ('
            . sprintf("%.2f%%", ($monthValue != 0?($monthProfit)/$monthValue:1) * 100)
            . ')'
        ],
        [
            'Year',
            sprintf("%01.2f USD", ($yearProfit))
            . ' ('
            . sprintf("%.2f%%", ($yearValue != 0?($yearProfit)/$yearValue:1) * 100)
            . ')'
        ],
        [
            'YTD',
            sprintf("%01.2f USD", ($ytdProfit))
            . ' ('
            . sprintf("%.2f%%", ($ytdValue != 0?($ytdProfit)/$ytdValue:1) * 100)
            . ')'
        ],
        [
            'All',
            sprintf("%01.2f USD", ($allProfit))
        ],
        // [
        //     'value' => $totalValue,
        //     'week' => ($weekValue != 0?($totalValue-$weekValue)/$weekValue:1),
        //     'month' => ($monthValue!=0?($totalValue-$monthValue)/$monthValue:1),
        //     'year' => ($yearValue!=0?($totalValue-$yearValue)/$yearValue:1),
        //     'all' => ($totalProfit)/100,
        //     'ytd' => ($ytdValue!=0?($totalValue-$ytdValue)/$ytdValue:1),
        // ],
        // [
        //     'value' => 'debug:value',
        //     'week' => ($weekValue),
        //     'month' => ($monthValue),
        //     'year' => ($yearValue),
        //     'all' => (''),
        //     'ytd' => (''),
        // ],
    ],
        ];
        $profitProvider = new ArrayDataProvider($data);

        return $this->render('dashboard', [
            'assetProvider' => $assetProvider,
            'profitProvider' => $profitProvider,
            'totalValue' => $totalValue,
            'totalLiabilityValue' => $totalLiabilityValue,
            'totalProfit' => $totalProfit,
            'filter' => $filter,
            'newsProvider' => $newsProvider,
            'eventProvider' => $eventProvider,
        ]);
    }

    public function actionIndex()
    {
        $query = Asset::find();
        $query->where('is_liability = 0');

        $assetProvider = new ActiveDataProvider(
            [
                'query' => $query,
                'sort'=> ['defaultOrder' => new Expression('name DESC')],
            ]
        );

        $cash = Asset::getOrCreateCash();

        $new_cash = new Transfer;
        $new_cash->asset_id = $cash->id;

        if ($new_cash->load(Yii::$app->request->post()) && $new_cash->save()) {
            //@todo fix this shit - get correct data
            $new_cash->asset_id = null;
            // $new_cash->amount_cash = $new_cash->amount;
            // $new_cash->amount = 0;
            $new_cash->save();
        }
        //var_dump($new_cash->errors);

        $query = Transfer::find()
            //->where(['asset_id' => $cash->id])
        ;
        $transferProvider = new ActiveDataProvider(
            [
                'query' => $query,
                'sort'=> ['defaultOrder' => ['created_at'=>SORT_DESC]],
            ]
        );

        $cashSum = $cash->value;


        return $this->render('index', [
            'assetProvider' => $assetProvider,
            'transferProvider' => $transferProvider,
            'cashSum' => $cashSum,
            'new_cash' => $new_cash,
        ]);
    }

    public function actionTransfer($id)
    {
        $query = Asset::find()
            ->where(['id' => $id])
        ;

        $asset = $query->one();

        $query = Transfer::find()
            ->where(['asset_id' => $asset->id])
            ->orderBy('created_at DESC, id DESC')
        ;

        $transferProvider = new ActiveDataProvider(
            [
                'query' => $query
            ]
        );

        $cash = Asset::getOrCreateCash();

        $transfer = new Transfer;
        $transfer->asset_id = $asset->id;

        if ($transfer->load(Yii::$app->request->post()) && $transfer->save()) {
            if ($cash->id != $asset->id) {
                //@todo Temporary fix. If we don't have price - update it
                if (!$asset->getPrice($transfer->created_at)) {
                    $price = $transfer->amount_usd / $transfer->amount;
                    $price = round($price, 8, PHP_ROUND_HALF_DOWN);
                    $asset->updatePrice($transfer->created_at, $price);
                }

            }
            $transfer->amount_cash = -$transfer->amount_usd;

            //@todo not like it
            if($asset->is_liability) {
                $transfer->amount_cash = -$transfer->amount_cash;
            }

            $transfer->save();

            $this->redirect(['transfer', 'id'=>$asset->id]);
        }

        return $this->render('transfer', [
            'asset' => $asset,
            'transfer' => $transfer,
            'transferProvider' => $transferProvider,
        ]);
    }

    public function actionProfit($id)
    {
        $query = Asset::find()
            ->where(['id' => $id])
        ;

        $asset = $query->one();

        $query = Profit::find()
            ->where(['asset_id' => $asset->id])
        ;

        $profitProvider = new ActiveDataProvider(
            [
                'query' => $query
            ]
        );

controllers/TransferController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Transfer;

class TransferController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => [
                            'ajax',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionAjax()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $result = new \stdclass;
        $id = Yii::$app->request->post('pk');
        $attribute = Yii::$app->request->post('name');
        $value = Yii::$app->request->post('value');

        $model = Transfer::find()->where(['id' => $id])->one();
        if($model) {
            $model[$attribute] = $value;
            $model->save();
            $result->id = $model->id;
            $result->text = 'saved';
        }

        return $result;
    }
}

views/portfolio/_cash_history.php
<?php
use yii\grid\GridView;
use yii\grid\CheckboxColumn;
use yii\grid\ActionColumn;
use yii\helpers\Html;
use app\models\Asset;

echo GridView::widget([
    'layout' => "
            <div class='panel panel-default'>
                <div class='panel-body'>
                    <legend>Cash History</legend>
                    {items}


                    <hr>
                    <div class='row'>
                        <div class='col-md-6'>{summary}</div>
                        <div class='col-md-6 text-right'>{pager}</div>
                    </div>
                </div>
            </div>

    ",
    'tableOptions' => [
        'class' => 'table table-striped table-hover'
    ],
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => CheckboxColumn::className()
        ],
        'id',
        [
            'attribute' => 'asset_id',
            'label' => 'Asset',
            'format' => 'raw',
            'value' => function ($model) {
                if (!$model->asset) {
                    $cash = Asset::getOrCreateCash();
                    return $cash->name;
                }

                $return = $model->asset->name;
                return $return;
            }
        ],
        [
            'label' => 'Amount',
            'format' => 'decimal',
            'value' => function ($model) {
                return $model->amount;
            }
        ],
        [
            'label' => 'Amount USD',
            'format' => 'currency',
            'attribute' => 'amount',
            'value' => function ($model) {
                return $model->amount_cash;
            }
        ],
        [
            'label' => 'Price USD (calculated)',
            'format' => 'currency',
            //'attribute' => 'amount',
            'value' => function ($model) {
                //@todo move method to model?
                return $model->amount_cash != 0 ? $model->amount / -$model->amount_cash : 0;
            }
        ],
        'comment',
        'created_at:date',
        [
            'class' => ActionColumn::className(),
            'template' => '{delete}',
            'contentOptions' => [
                'class' => 'text-right'
            ],
            'buttons' => [
                'delete' => function ($url, $model, $key) {
                    return Html::a(
                        '<i class="fa fa-trash"></i> Delete',
                        [
                        '/portfolio/transfer-delete',
                        'transfer_id' => $model->id
                    ],
                        ['class' => 'btn btn-xs btn-danger delete-button', 'data-id' => $model->id]
                    );
                }
            ]
        ]
    ]
]);

views/portfolio/asset-update.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Asset '.($asset->isNewRecord?'Create':'Update '.$asset->name);
$this->params['breadcrumbs'][] = ['label' => 'Portfolio', 'url' => ['index']];;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portfolio-asset">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-12">
            <?php $model = $asset?>
            <?php $form = ActiveForm::begin([]); ?>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php //echo $form->field($model, 'name')->label(true)->textInput(['placeholder' => 'Name']) ?>
                    <?php echo $form->field($model, 'name')->widget(kartik\select2\Select2::classname(), [
                        'data' => \app\models\Asset::getAssetData($model->name),
                        'options' => ['placeholder' => 'Select an asset ...'],
                        'pluginOptions' => [
                            // 'allowClear' => true,
                            // 'selectOnBlur' => true,
                            // 'selectOnClose' => true,
                            'tags' => true,
                            // 'createTag' => 'function (params) {
                            //     return {
                            //       id: params.term,
                            //       text: params.term
                            //     }
                            //   }',
                        ],
                    ]);?>

                    
                    <?php echo $form->field($model, 'type')->dropDownList(\app\models\Asset::TYPE); ?>
                    <?php echo $form->field($model, 'is_auto_update')->checkbox(); ?>
                    <?php echo $form->field($model, 'comment')->inline(); ?>

                    <hr>
                    <div class="text-center">
                        <div class="btn-group" role="group">
                            <?= Html::submitButton('<i class="fa fa-check"></i> Submit', ['class' => 'btn btn-primary']) ?>
                        </div>
                    </div>
                </div>
                <?php $form::end(); ?>
        </div>
    </div>
</div>

views/portfolio/charts.php
<?php

/**
 * @var $this \yii\web\View
 * @var $dateFrom string
 * @var $dateTo string
 */

use app\assets\GCExternalAsset;
use app\models\Statistic;
use yii\helpers\Json;
use yii\helpers\Url;

GCExternalAsset::register($this);
list($origLoggedDate, $loggedData) = Statistic::getLoggedData($dateFrom, $dateTo, true);

$this->registerJs('var userStatsUrl = "' . Url::to(['/admin/users-statistic'], true) . '"', $this::POS_HEAD);
$this->registerJs('var dataLogged = ' . Json::encode($loggedData), $this::POS_HEAD);
$this->registerJs('var origLoggedDate = ' . Json::encode($origLoggedDate), $this::POS_HEAD);
?>

<div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">Chart</div>
                <div class="panel-body text-center">
                    <div id="chart-logged"></div>
                </div>
            </div>
        </div>
    <?php if (count($loggedData) > 2) { ?>
    <?php } ?>

</div>

views/portfolio/price-update.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use kartik\date\DatePicker;

$this->title = 'Price '.($price->isNewRecord?'Create':'Update #'.$price->id);
$this->params['breadcrumbs'][] = ['label' => 'Portfolio', 'url' => ['index']];;
$this->params['breadcrumbs'][] = ['label' => 'Price '.$asset->name, 'url' => ['price', 'id'=>$asset->id]];;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portfolio-price">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-12">
            <?php $model = $price?>
            <?php $form = ActiveForm::begin([]); ?>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?= $form->field($model, 'amount')->label(true)->textInput(['placeholder' => 'Amount']) ?>
                    <?= $form->field($model, 'created_at')->widget(DatePicker::classname(), [
                        'options' => ['placeholder' => 'Enter date ...'],
                        'pluginOptions' => [
                            'todayHighlight' => true,
                            'todayBtn' => true,
                            'autoclose'=>true,
                            'format' => 'yyyy-mm-dd',
                            'convertFormat' => true,
                        ]
                    ]);?>

                    <hr>
                    <div class="text-center">
                        <div class="btn-group" role="group">
                            <?= Html::submitButton('<i class="fa fa-check"></i> Submit', ['class' => 'btn btn-primary']) ?>
                        </div>
                    </div>
                </div>
                <?php $form::end(); ?>
        </div>
    </div>
</div>

views/portfolio/price.php
<?php

use yii\grid\ActionColumn;
use yii\grid\CheckboxColumn;
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Price '.$asset->name;
$this->params['breadcrumbs'][] = ['label' => 'Portfolio', 'url' => ['index']];;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portfolio-price">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-12">
            <?php
            echo GridView::widget(
                [
                    'layout' => "
                            <div class='panel panel-default'>
                                <div class='panel-body'>
                                    <div class='row'>
                                        <div class='col-md-12 text-right'>
                                            " . Html::a('<i class="fa fa-plus"></i> Add new', ['price-update',
                            'id' => $asset->id,
                        ],
                            ['class' => 'btn btn-success']) . "
                                        </div>
                                    </div>

                                    <hr>

                                    {items}


                                    <hr>
                                    <div class='row'>
                                        <div class='col-md-6'>{summary}</div>
                                        <div class='col-md-6 text-right'>{pager}</div>
                                    </div>
                                </div>
                            </div>

                    ",
                    'tableOptions' => [
                        'class' => 'table table-striped table-hover'
                    ],
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        [
                            'class' => CheckboxColumn::className()
                        ],
                        'id',
                        'amount:currency',
                        'created_at:date',
                        [
                            'class' => ActionColumn::className(),
                            'template' => '{update} {delete}',
                            'contentOptions' => [
                                'class' => 'text-right'
                            ],
                            'buttons' => [
                                'update' => function ($url, $model, $key) use ($asset) {
                                    return Html::a('<i class="fa fa-edit"></i> Edit', [
                                        'price-update',
                                        'id' => $asset->id,
                                        'price_id' => $model->id,
                                    ], ['class' => 'btn btn-xs btn-success']
                                    );
                                },
                                'delete' => function ($url, $model, $key) use ($asset) {
                                    return Html::a('<i class="fa fa-trash"></i> Delete', [
                                        'price-delete',
                                        'id' => $asset->id,
                                        'price_id' => $model->id,
                                    ], ['class' => 'btn btn-xs btn-danger delete-button', 'data-id' => $model->id]
                                    );
                                }
                            ]
                        ]
                    ]
                ]
            );
            ?>


        </div>
    </div>
</div>

views/portfolio/transfer.php
<?php

use yii\grid\ActionColumn;
use yii\grid\CheckboxColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;

$this->title = 'Transfer from/to '.$asset->name;
$this->params['breadcrumbs'][] = ['label' => 'Portfolio', 'url' => ['index']];;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portfolio-transfer">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-lg-4">
            <?php $model = $transfer?>
            <?php $form = ActiveForm::begin([]); ?>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php echo $form->field($model, 'amount_usd')->label(true)->textInput(['placeholder' => 'Amount: positive if from cash, negative if to cash']) ?>
                    <?= $form->field($model, 'amount')->label(true)->textInput(['placeholder' => 'Asset currency']) ?>
                    <?= $form->field($model, 'created_at')->widget(DatePicker::classname(), [
                        'options' => ['placeholder' => 'Enter date ...'],
                        'pluginOptions' => [
                            'todayHighlight' => true,
                            'todayBtn' => true,
                            'autoclose'=>true,
                            'format' => 'yyyy-mm-dd',
                        ]
                    ]);?>

                    <hr>
                    <div class="text-center">
                        <div class="btn-group" role="group">
                            <?= Html::submitButton('<i class="fa fa-check"></i> Submit', ['class' => 'btn btn-primary']) ?>
                        </div>
                    </div>
                </div>
                <?php $form::end(); ?>
            </div>
        </div>

        <div class="col-lg-8">
            <?php
            echo GridView::widget(
                [
                    'layout' => "
                            <div class='panel panel-default'>
                                <div class='panel-body'>
                                    <legend>History</legend>

                                    {items}

                                    <hr>
                                    <div class='row'>
                                        <div class='col-md-6'>{summary}</div>
                                        <div class='col-md-6 text-right'>{pager}</div>
                                    </div>
                                </div>
                            </div>

                    ",
                    'tableOptions' => [
                        'class' => 'table table-striped table-hover'
                    ],
                    'dataProvider' => $transferProvider,
                    'columns' => [
                        [
                            'class' => CheckboxColumn::className()
                        ],
                        'id',
                        // 'amount_usd:currency',
                        [
                            'header' => 'Amount (Asset)',
                            'format' => 'decimal',
                            'attribute' => 'amount',
                        ],
                        [
                            'header' => 'Amount (USD)',
                            'format' => 'currency',
                            'value' => function($model) {
                                return $model->amount_cash;
                            }
                        ],
                        [
                            'header' => 'Rate',
                            'value' => function($model) {
                                return -$model->amount ? $model->amount_cash / $model->amount : 0;
                            }
                        ],
                        // [
                        //     'attribute' => 'amount',
                        //     'value' => function($model) {
                        //         return $model->amount;
                        //     }
                        // ],
                        'created_at:date',
                        [
                            'class' => \yii2mod\editable\EditableColumn::class,
                            'attribute' => 'comment',
                            'url' => ['/transfer/ajax'],
                         ],                        
                        [
                            'class' => ActionColumn::className(),
                            'template' => '{delete}',
                            'contentOptions' => [
                                'class' => 'text-right'
                            ],
                            'buttons' => [
                                'delete' => function ($url, $model, $key) use ($asset) {
                                    return Html::a('<i class="fa fa-trash"></i> Delete', [
                                        'transfer-delete',
                                        'id' => $asset->id,
                                        'transfer_id' => $model->id,
                                    ], ['class' => 'btn btn-xs btn-danger delete-button', 'data-id' => $model->id]
                                    );
                                }
                            ]
                        ]
                    ]
                ]
            );
            ?>


        </div>
    </div>
</div>